### ISSUE TITLE
Conflict Detection Modifications

### ISSUE THREAD

**Issue by liangjunlang** [Kei18/lacam#16]
Hello, suppose I need to do a follow-up conflict detection, how should I modify it? For example, the position of agent B at the next moment cannot be the position of agent A at that moment. How should I modify it in the code?

**Comment by Kei18** [comment]
Hello, it is possible to introduce the following conflicts. You can start by considering how to apply A* to such a scenario.

Code example - sorry, I do not have a public one.

**Comment by liangjunlang** [comment]
您的邮件已收到，我会仔细阅读的。
